# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba7aa4ed9b7230c259e590db79f38699b40c283a3eb3784a0c2b1ff41eb11fa6f643a807d05086dd8a88794ca1c3854388028f067db1b5060a59310926833111

test:
  secret_key_base: e7c3c9892f0cb84e1f56cbb9071542a8327b28c3ab4e75a9113eaffea32faf70ad962c785b1bb36ec467361ea6172aa1c89521cfbe236ba88c09cba04f85a8b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
